# Generated by Django 4.1.7 on 2023-03-03 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_starting_bid_auctionlisting_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='users_watching',
            field=models.ManyToManyField(blank=True, default=None, related_name='users_watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
