# Generated by Django 4.1.7 on 2023-03-04 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlisting_users_watching'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='current_price',
            new_name='starting_price',
        ),
    ]
