# Generated by Django 4.1.7 on 2023-03-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_bid_listing_id_bid_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('CLOTHING', 'Clothing & Accessories'), ('HEALTH', 'Health & Beauty'), ('FITNESS', 'Fitness'), ('JEWELRY', 'Jewelry'), ('PET', 'Pet Supplies'), ('MOBILE', 'Mobile Phones & Accessories'), ('Cameras & Photos', 'Cameras & Photos')], max_length=20),
        ),
    ]
