# Generated by Django 4.1.7 on 2023-03-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctionlisting_active_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
