# Generated by Django 4.1.7 on 2023-03-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_author_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
